version: "2"

services:
  postgres:
    image: centos/postgresql-95-centos7
    container_name: "postgres"
    ports:
      - 5432:5432
    labels:
      kompose.volume.size: 512M
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USER=plataforma 
      - POSTGRESQL_PASSWORD=qazwsx
      - POSTGRESQL_DATABASE=plataforma
  mongo:
    image: openshift/mongodb-24-centos7
    container_name: "mongo"
    ports:
      - 27017:27017
    labels:
      kompose.volume.size: 512M
    volumes:
      - mongo-data:/var/lib/mongodb
    environment:
      - MONGODB_USER=plataforma
      - MONGODB_PASSWORD=qazwsx
      - MONGODB_DATABASE=plataforma
      - MONGODB_ADMIN_PASSWORD=qazwsx
  process-memory:
    image: "onsplataforma/process-memory"
    build:
      context: ./Dockerfiles
      dockerfile: DProcessMemory
    container_name: "process-memory"
    ports:
      - 9091:9091
    environment:
      - MONGO_HOST=mongo
  apicore:
    image: "onsplataforma/apicore"
    build:
      context: ./Dockerfiles
      dockerfile: DApiCore
    container_name: "apicore"
    ports:
      - 9110:9110
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - PROCESS_MEMORY_PORT=9091
      - COREAPI_URL=apicore
      - COREAPI_PORT=9110
  event-manager:
    image: "onsplataforma/event-manager"
    build:
      context: ./Dockerfiles
      dockerfile: DEventManager
    container_name: "event-manager"
    ports:
      - 8081:8081
    environment:
      - EXECUTOR_HOST=executor
      - REPLAY_HOST=replay
      - PROCESS_MEMORY_HOST=process-memory
      - ROUTER_HOST=http_router
      - INFLUX_HOST=influxdb
      - APICORE_HOST=apicore
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_API_PORT=15672
      - RABBITMQ_AMQP_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MONGO_HOST=mongo:27017
      - MAESTRO_HOST=maestro
    depends_on:
      - "rabbitmq"
      - "postgres"
  maestro:
    image: "onsplataforma/maestro"
    build:
      context: ./Dockerfiles
      dockerfile: DMaestro
    container_name: "maestro"
    ports:
      - 6971:6971
    environment:
      - EXECUTOR_HOST=executor
      - DISCOVERY_HOST=discovery
      - PROCESS_MEMORY_HOST=process-memory
      - ROUTER_HOST=http_router
      - INFLUX_HOST=influxdb
      - APICORE_HOST=apicore
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_API_PORT=15672
      - RABBITMQ_AMQP_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MONGO_HOST=mongo:27017
      - EVENT_MANAGER_HOST=event-manager
      - WAUTO_REPROCESSING_ec498841-59e5-47fd-8075-136d79155705=True
    depends_on:
      - "onsplataforma/event-manager"
      - "apicore"
      - "discovery"
      - "rabbitmq"
      - "process-memory"
  discovery:
    image: "onsplataforma/discovery"
    build:
      context: ./Dockerfiles
      dockerfile: DDiscovery
    container_name: "discovery"
    ports:
      - 8090:8090
    environment:
      - PROCESS_MEMORY_HOST=process-memory
      - APICORE_HOST=apicore
      - POSTGRES_HOST=postgres
    depends_on:
      - "onsplataforma/apicore"
      - "process-memory"
      - "rabbitmq"
      - "postgres"
  ui:
    image: "onsplataforma/ui"
    build:
      context: ./Dockerfiles
      dockerfile: DFront
    container_name: "ui"
    ports:
      - 8384:8384
    environment:
      - PROCESS_MEMORY_HOST=process-memory
      - REPLAY_HOST=replay
      - APICORE_HOST=apicore
      - EVENT_MANAGER_HOST=event-manager
      - MAESTRO_HOST=maestro
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_API_PORT=15672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - "onsplataforma/apicore"
      - "process-memory"
      - "event-manager"
      - "rabbitmq"
      - "postgres"
  executor:
    image: "onsplataforma/executor"
    build:
      context: ./Dockerfiles
      dockerfile: DExecutor
    container_name: "executor"
    environment:
      - PROCESS_MEMORY_URL=process-memory
      - PROCESS_MEMORY_PORT=9091
      - COREAPI_URL=apicore
      - COREAPI_PORT=9110
      - EVENT_MANAGER_URL=event-manager
      - EVENT_MANAGER_PORT=8081
      - EXEC=gunicorn -b :8000 runner.api:runner_api
    ports:
      - 8000:8000
  authprovider:
    image: "onsplataforma/authprovider"
    build:
      context: ./Dockerfiles
      dockerfile: DAuthProvider
    container_name: "authprovider"
    environment:
      - PORT=8085
    ports:
      - 8085:8085
  celery:
    image: "onsplataforma/celery"
    build:
      context: ./Dockerfiles
      dockerfile: DCelery
    container_name: "celery"
    environment:
      - DEBUG_MODE=True
      - REMOVE_CONTAINER_AFTER_EXECUTION=False
      - PROCESS_MEMORY_URL=process-memory
      - PROCESS_MEMORY_PORT=9091
      - COREAPI_URL=apicore
      - COREAPI_PORT=9110
      - EVENT_MANAGER_URL=event-manager
      - EVENT_MANAGER_PORT=8081
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - C_FORCE_ROOT=true
    depends_on:
      - "onsplataforma/event-manager"
      - "rabbitmq"
      - "postgres"
  influxdb:
    image: robertbohne/influxdb
    container_name: "influxdb"
    ports:
      - "8086:8086"
  rabbitmq:
    image:  rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
networks:
  default:
    external:
      name: plataforma_network
