version: "2"

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    container_name: "adminer"
    ports:
      - 8080:8080
  pgadmin:
    image: fenglc/pgadmin4:latest
    container_name: "pgadmin"
    ports:
      - 5050:5050
  apicore:
    build:
      context: ./Dockerfiles
      dockerfile: ApiCore
    container_name: "apicore"
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 9100:9110
  process_memory:
    build:
      context: ./Dockerfiles
      dockerfile: ProcessMemory
    container_name: "process_memory"
    ports:
      - 9091:9091
  event_manager:
    build:
      context: ./Dockerfiles
      dockerfile: EventManager
    container_name: "event_manager"
    ports:
      - 8081:8081
    environment:
      - EXECUTOR_HOST=executor
      - ROUTER_HOST=http_router
  executor:
    build:
      context: ./Dockerfiles
      dockerfile: Executor
    container_name: "executor"
    ports:
      - 8000:8000
  registry:
    image: "registry:2"
    container_name: "registry"
    ports:
      - 5000:5000

